### Exercises

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [13]:
import torch
# Create a random tensor with shape (7, 7).

tensor1 = torch.rand(7, 7)
tensor1

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [15]:
tensor2 = torch.rand(1, 7)
tensor2 = tensor2.T

# matrix mult
matmulTensor = torch.matmul(tensor1, tensor2)
matmulTensor, matmulTensor.shape

(tensor([[1.8249],
         [2.3089],
         [2.6509],
         [1.5015],
         [2.0858],
         [2.0102],
         [2.9746]]),
 torch.Size([7, 1]))

In [16]:
# Set the random seed to 0 and do exercises 2 & 3 over again.

RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(1, 7).T

tensorMatMul = torch.matmul(tensorA, tensorB)
tensorMatMul, tensorMatMul.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [19]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed()
# but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)

In [22]:
device = 'mps'

random_seed = 1234
torch.manual_seed(random_seed)
tensorC = torch.rand(2, 3).to(device)

torch.manual_seed(random_seed)
tensorD = torch.rand(2, 3).to(device)
tensorC, tensorD

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'))

In [23]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

tensorMatMul2 = torch.matmul(tensorC, tensorD.T)
tensorMatMul2, tensorMatMul2.shape


(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='mps:0'),
 torch.Size([2, 2]))

In [24]:
torch.max(tensorMatMul2)

tensor(0.6287, device='mps:0')

In [32]:
torch.min(tensorMatMul2)

tensor(0.2161, device='mps:0')

In [33]:
in_max = torch.argmax(tensorMatMul2)
in_min = torch.argmin(tensorMatMul2)

in_max, in_min

(tensor(3, device='mps:0'), tensor(1, device='mps:0'))

In [36]:
torch.manual_seed(7)

tensor3 = torch.rand(1, 1, 1, 10)
tensor4 = tensor3.squeeze()
print(tensor3, tensor3.shape)
print(tensor4, tensor4.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
