## Tensor is a data structure used to store and manipulate data

- Multidimensional array containing elements of single data type.
- Tensors represents scalar, vectors, matrices and n-multidimensional arrays, derived from <italic>torch</italic>

In [1]:
import torch

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]]);
y = torch.tensor([[7, 8, 9], [10, 11, 12]]);
print(x)
print(y)
z = x + y
print("Adding", z)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Adding tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [4]:
z_mult = x * y
print(z_mult)

tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [5]:
z_div = x / y;
print(z_div)

tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


In [6]:
print(z.size())

torch.Size([2, 3])


In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [9]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], device=device)

z = x + y
print(z)
print(z.size())
print(z.device)


tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])
cpu


In [10]:
import numpy

